# vim:sw=2:ts=2
# action name
name: 'phoenix-build'

# action author
author: 'Marek Białowąs <marek.bialowas@phoenix-rtos.com>'

# action description
description: 'Builds Phoenix-RTOS based projects'

# action input values
inputs:
  target:
    description: 'Target env variable'
    default: 'ia32-generic'
    required: false
  syspage:
    description: 'Syspage env variable'
    default: ''
    required: false
  long_test:
    description: 'Env variable for building long tests'
    default: ''
    required: false
  # github doesn't allow array of arguments, we need to pass them one-by-one
  param1:
    description: 'Parameters to the main build script - 1st param'
    default: 'clean'
    required: false
  param2:
    description: 'Parameters to the main build script - 2nd param'
    default: ''
    required: false
  param3:
    description: 'Parameters to the main build script - 3rd param'
    default: ''
    required: false
  param4:
    description: 'Parameters to the main build script - 4th param'
    default: ''
    required: false
  param5:
    description: 'Parameters to the main build script - 5th param'
    default: ''
    required: false
  param6:
    description: 'Parameters to the main build script - 6th param'
    default: ''
    required: false

# action runner
runs:
  using: 'docker'
  image: 'phoenixrtos/build'
  env:
    CONSOLE: 'serial'
    TARGET: ${{ inputs.target }}
    SYSPAGE: ${{ inputs.syspage }}
    LONG_TEST:  ${{ inputs.long_test }}
  args:
    - ${{ inputs.param1 }}
    - ${{ inputs.param2 }}
    - ${{ inputs.param3 }}
    - ${{ inputs.param4 }}
    - ${{ inputs.param5 }}
    - ${{ inputs.param6 }}


# branding
branding:
  icon: terminal
  color: green
