# vim:sw=2:ts=2
# action name
name: 'phoenix-runner'

# action description
description: 'Runs Phoenix-RTOS tests'

inputs:
  target:
    description: 'Specifies target to run tests'
    default: 'ia32-generic'
    required: false

  long_test:
    description: 'If specified long tests are run too'
    default: ''
    required: false


# action runner
runs:
  using: 'docker'
  image: 'phoenixrtos/devel'
  entrypoint: ./phoenix-rtos-tests/runner.py
  args:
    - '-T${{ inputs.target }}'
    # "--long-test" "True" enables long tests
    # "--long-test" "" disables long tests - default
    - '--long-test' 
    - '${{ inputs.long_test }}'

# branding
branding:
  icon: terminal
  color: green
