# vim:sw=2:ts=2
name: ci

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  call-ci:
    uses: phoenix-pilot/phoenix-pilot-project/.github/workflows/ci-project.yml@PNieck/enable_CI
    secrets: inherit
